# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Gloo.cli
PackageVersion: 0.1.6
InstallerType: portable
Commands:
- gloo
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/GlooHQ/homebrew-gloo/releases/download/0.1.1/gloo.exe
  InstallerSha256: E1B6AAA2CE072B003FA30A4747A3ED6ED9C1D868BF377E1E9D0F2CFB00439572
ManifestType: installer
ManifestVersion: 1.5.0
